[project]
name = "code-executor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bullmq>=2.26.0",
    "docker>=7.2.0",
    "fastapi>=0.140.0",
    "httpx>=0.28.1",
    "locust>=2.46.2",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.32",
    "redis>=7.4.0",
    "uvicorn>=0.51.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
exclude = ["docker*", "frontend*", "images*", "scripts*"]
